### PR TITLE
Add the Jpn translation v606

### PR DESCRIPTION
**Pull request by classicarma**
Add the Japanese translation to v606

### CODE REVIEW

**Comment by Mickyleitor** [comment]
Thanks! It would be updated in the next release!

**Comment by classicarma** [comment]
@Mickyleitor Cool

**Comment by classicarma** [comment]
@Mickyleitor I think that it would be good if I can translate Lythium maps

**Comment by Mickyleitor** [comment]
Yeah I'll try it but as I don't own currently the source files I may convince the guy who is working with lythium to deal with the stringtable stuff. However It should be added at some point.

**Pull request merged**
